spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"

server:
 port: 8071




#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Prasanth-Thottempudi/config-repo
#          username: Prasanth-Thottempudi
#          password: Adolf@git123
