server:
  port: 8071

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Prasanth-Thottempudi/config-repo
          username: Prasanth-Thottempudi
          password: Adolf@git123
