server:
  port: 8080

spring:
  application:
    name: "user"  # Ensure this matches your service name

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    import: "configserver:http://localhost:8888/"

  rabbitmq:
    host: "localhost"
    port: 5672  # Default port
    username: "guest"
    password: "guest"
  cloud:
   bus:
     enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
