server:
  port: 8080

spring:
  application:
    name: "user"  # Rename this to match your service's name (e.g., usermanagement)
#  profiles:
#    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Import configuration from the Config Server (change port if needed)
  config:
    import: "configserver:http://localhost:8888/"
